# Generated by Django 3.2.7 on 2021-10-04 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borabora', '0002_auto_20211004_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='timestam',
            new_name='timestamp',
        ),
    ]
