# Generated by Django 3.2.7 on 2021-10-04 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borabora', '0004_rename_timestamp_comment_timestam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='timestam',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_child',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Текст комментарии'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
