# Generated by Django 3.2.7 on 2021-10-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borabora', '0007_comment_is_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
